/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.siem.deep;import cn.zhuatech.siem.common.ApiResponse;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;/**
                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                           */
@RestController @RequestMapping("/api/siem-ops") public class DeepDomainController{private final DeepDomainService s;/**
                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                */
public DeepDomainController(DeepDomainService s){this.s=s;}/**
                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                           */
@GetMapping("/dashboard")ApiResponse<?> dashboard(@RequestParam String organizationCode){return ApiResponse.ok(s.dashboard(organizationCode));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */
@PostMapping("/sources")ApiResponse<?> source(@Valid @RequestBody DeepDomainService.SourceRequest r){return ApiResponse.ok(s.source(r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
@PostMapping("/sources/{id}/events")ApiResponse<?> ingest(@PathVariable Long id,@Valid @RequestBody DeepDomainService.EventRequest r){return ApiResponse.ok(s.ingest(id,r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
@PostMapping("/incidents/{id}/assign")ApiResponse<?> assign(@PathVariable Long id,@Valid @RequestBody DeepDomainService.AssignRequest r){return ApiResponse.ok(s.assign(id,r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
@PostMapping("/incidents/{id}/investigate")ApiResponse<?> investigate(@PathVariable Long id,@Valid @RequestBody DeepDomainService.InvestigationRequest r){return ApiResponse.ok(s.investigate(id,r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */
@PostMapping("/incidents/{id}/respond")ApiResponse<?> respond(@PathVariable Long id,@Valid @RequestBody DeepDomainService.ResponseRequest r){return ApiResponse.ok(s.respond(id,r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
@PostMapping("/incidents/{id}/recover")ApiResponse<?> recover(@PathVariable Long id){return ApiResponse.ok(s.recover(id));}}
