/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.siem.deep;import cn.zhuatech.siem.model.AuditLog;import cn.zhuatech.siem.repository.AuditLogRepository;import jakarta.persistence.*;import jakarta.validation.constraints.*;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.server.ResponseStatusException;import java.time.*;import java.util.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Service @Transactional(readOnly=true) public class DeepDomainService{private final EntityManager em;private final AuditLogRepository logs;/**
                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                            */
public DeepDomainService(EntityManager e,AuditLogRepository l){em=e;logs=l;}/**
                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                        */
public Dashboard dashboard(String o){return new Dashboard(sources(o),rules(o),incidents(o));}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public SourceView source(SourceRequest r){var s=new SecurityLogSource(r.organizationCode(),r.sourceCode(),r.name(),r.sourceType());em.persist(s);audit("SIEM_SOURCE","登记日志源",s.sourceCode,s.sourceType);return view(s);}/**
                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                         */
@Transactional public SourceView activate(Long id){var s=source(id);if(!"DRAFT".equals(s.status))throw conflict("只有草稿日志源可以启用");s.status="ACTIVE";audit("SIEM_SOURCE","启用日志源",s.sourceCode,s.name);return view(s);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
@Transactional public RuleView rule(RuleRequest r){if(r.minimumSeverity()<0||r.minimumSeverity()>100)throw bad("最低风险分必须在0到100之间");var x=new DetectionRule(r.organizationCode(),r.ruleCode(),r.name(),r.eventType(),r.minimumSeverity(),r.incidentSeverity());em.persist(x);audit("SIEM_RULE","发布检测规则",x.ruleCode,x.eventType);return view(x);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public IngestResult ingest(Long sourceId,EventRequest r){var s=source(sourceId);if(!"ACTIVE".equals(s.status))throw conflict("日志源未启用");long duplicate=em.createQuery("select count(e) from SecurityEvent e where e.eventId=:eventId",Long.class).setParameter("eventId",r.eventId()).getSingleResult();if(duplicate>0)throw conflict("安全事件编号已存在");var e=new SecurityEvent(r.eventId(),sourceId,r.eventType(),r.severityScore(),r.principal(),r.asset(),r.summary(),r.occurredAt());em.persist(e);s.lastEventAt=LocalDateTime.now();var matched=em.createQuery("select x from DetectionRule x where x.organizationCode=:o and x.eventType=:t and x.status='ACTIVE' and x.minimumSeverity<=:score order by x.minimumSeverity desc",DetectionRule.class).setParameter("o",s.organizationCode).setParameter("t",r.eventType()).setParameter("score",r.severityScore()).setMaxResults(1).getResultStream().findFirst().orElse(null);Long incidentId=null;if(matched!=null){var i=new SecurityIncident(e.id,matched.id,"INC-"+r.eventId(),matched.incidentSeverity);em.persist(i);incidentId=i.id;}audit("SIEM_EVENT","接收安全事件",r.eventId(),matched==null?"NO_MATCH":"MATCH "+matched.ruleCode);return new IngestResult(view(e),matched==null?null:matched.ruleCode,incidentId);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public IncidentView assign(Long id,AssignRequest r){var i=incident(id);state(i,"OPEN");i.assignee=r.assignee();i.status="INVESTIGATING";audit("SIEM_INCIDENT","分派事件",i.incidentNo,r.assignee());return view(i);}/**
                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                 */
@Transactional public IncidentView investigate(Long id,InvestigationRequest r){var i=incident(id);state(i,"INVESTIGATING");if(!r.evidenceHash().matches("[a-fA-F0-9]{64}"))throw bad("证据摘要必须为64位SHA-256");i.investigationNote=r.note();i.evidenceHash=r.evidenceHash().toLowerCase();i.status="READY_RESPONSE";audit("SIEM_INCIDENT","完成调查",i.incidentNo,r.note());return view(i);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
@Transactional public IncidentView respond(Long id,ResponseRequest r){var i=incident(id);state(i,"READY_RESPONSE");i.responseAction=r.action();i.status="CONTAINED";audit("SIEM_INCIDENT","执行遏制",i.incidentNo,r.action());return view(i);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
@Transactional public IncidentView recover(Long id){var i=incident(id);state(i,"CONTAINED");i.status="RECOVERED";audit("SIEM_INCIDENT","业务恢复",i.incidentNo,i.responseAction);return view(i);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
@Transactional public IncidentView close(Long id,CloseRequest r){var i=incident(id);state(i,"RECOVERED");if(i.evidenceHash==null)throw conflict("缺少调查证据不能关闭事件");i.status="CLOSED";i.closedAt=LocalDateTime.now();audit("SIEM_INCIDENT","关闭安全事件",i.incidentNo,r.note());return view(i);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 private List<SourceView>sources(String o){return em.createQuery("select s from SecurityLogSource s where s.organizationCode=:o order by s.createdAt desc",SecurityLogSource.class).setParameter("o",o).getResultList().stream().map(this::view).toList();}/**
                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                            */
private List<RuleView>rules(String o){return em.createQuery("select r from DetectionRule r where r.organizationCode=:o order by r.id desc",DetectionRule.class).setParameter("o",o).getResultList().stream().map(this::view).toList();}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
private List<IncidentView>incidents(String o){return em.createQuery("select i from SecurityIncident i where i.eventId in(select e.id from SecurityEvent e where e.sourceId in(select s.id from SecurityLogSource s where s.organizationCode=:o)) order by i.createdAt desc",SecurityIncident.class).setParameter("o",o).getResultList().stream().map(this::view).toList();}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
private SecurityLogSource source(Long id){var x=em.find(SecurityLogSource.class,id);if(x==null)throw missing("日志源不存在");return x;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               */
private SecurityIncident incident(Long id){var x=em.find(SecurityIncident.class,id);if(x==null)throw missing("安全事件不存在");return x;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 */
private void state(SecurityIncident i,String s){if(!s.equals(i.status))throw conflict("当前安全事件状态不能执行该操作");}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
private void audit(String m,String a,String n,String d){logs.save(new AuditLog(m,a,n,"siem-domain",d));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
private ResponseStatusException bad(String m){return new ResponseStatusException(HttpStatus.BAD_REQUEST,m);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               */
private ResponseStatusException conflict(String m){return new ResponseStatusException(HttpStatus.CONFLICT,m);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             */
private ResponseStatusException missing(String m){return new ResponseStatusException(HttpStatus.NOT_FOUND,m);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 private SourceView view(SecurityLogSource s){return new SourceView(s.id,s.organizationCode,s.sourceCode,s.name,s.sourceType,s.status,s.lastEventAt);}/**
                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                       */
private RuleView view(DetectionRule r){return new RuleView(r.id,r.organizationCode,r.ruleCode,r.name,r.eventType,r.minimumSeverity,r.incidentSeverity,r.status);}/**
                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                        */
private EventView view(SecurityEvent e){return new EventView(e.id,e.eventId,e.sourceId,e.eventType,e.severityScore,e.principal,e.asset,e.summary,e.occurredAt);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
private IncidentView view(SecurityIncident i){return new IncidentView(i.id,i.eventId,i.ruleId,i.incidentNo,i.severity,i.status,i.assignee,i.investigationNote,i.evidenceHash,i.responseAction,i.createdAt,i.closedAt,i.version);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 public record SourceRequest(@NotBlank String organizationCode,@NotBlank String sourceCode,@NotBlank String name,@NotBlank String sourceType){}/**
                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                */
public record RuleRequest(@NotBlank String organizationCode,@NotBlank String ruleCode,@NotBlank String name,@NotBlank String eventType,@Min(0)@Max(100)int minimumSeverity,@NotBlank String incidentSeverity){}/**
                                                                                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                               */
public record EventRequest(@NotBlank String eventId,@NotBlank String eventType,@Min(0)@Max(100)int severityScore,@NotBlank String principal,@NotBlank String asset,@NotBlank String summary,@NotNull LocalDateTime occurredAt){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               */
public record AssignRequest(@NotBlank String assignee){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
public record InvestigationRequest(@NotBlank String note,@NotBlank String evidenceHash){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
public record ResponseRequest(@NotBlank String action){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
public record CloseRequest(@NotBlank String note){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
public record SourceView(Long id,String organizationCode,String sourceCode,String name,String sourceType,String status,LocalDateTime lastEventAt){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
public record RuleView(Long id,String organizationCode,String ruleCode,String name,String eventType,int minimumSeverity,String incidentSeverity,String status){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
public record EventView(Long id,String eventId,Long sourceId,String eventType,int severityScore,String principal,String asset,String summary,LocalDateTime occurredAt){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */
public record IncidentView(Long id,Long eventId,Long ruleId,String incidentNo,String severity,String status,String assignee,String investigationNote,String evidenceHash,String responseAction,LocalDateTime createdAt,LocalDateTime closedAt,long version){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
public record IngestResult(EventView event,String matchedRule,Long incidentId){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
public record Dashboard(List<SourceView>sources,List<RuleView>rules,List<IncidentView>incidents){}
}
